apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-app
spec:
  replicas: 2  # Number of Pods
  selector:
    matchLabels:
      app: kubernetes-test-app
  template:
    metadata:
      labels:
        app: kubernetes-test-app
    spec:
      containers:
      - name: kubernetes-test-app
        image: kubernetes-test-app:latest
        imagePullPolicy: Never  # Use local image (loaded into minikube)
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-app
spec:
  selector:
    app: kubernetes-test-app
  type: NodePort   # Expose outside cluster
  ports:
  - port: 8080       # Service Port (inside cluster)
    targetPort: 5000 # Container port
    nodePort: 30007  # Fixed NodePort (30000–32767)
